spring:
  application:
    name : FlightBookingMicroService
server:
  port: ${port:9003}
management:
     security:
         enabled: false
eureka:
  client:
     serviceUrl:
       defaultZone: http://localhost:9006/eureka/

